apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: javawebapprs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: javawebapp
  template:
    metadata:
      name: javawebapppod
      labels:
        app: javawebapp
    spec: 
      volumes:
      - name: tomcatconf
        configMap: 
          name: tomcatuserconf
          items:
          - key: "tomcat-users.xml"
            path: "tomcat-users.xml"
      containers:
      - name: javawebcontainer
        image: dockerhandson/java-web-app:1
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: tomcatconf
          mountPath: /usr/local/tomcat/conf/tomcat-users.xml
          subPath: "tomcat-users.xml"
---
apiVersion: v1
kind: Service
metadata:
  name: javawebapp-svc
spec:
  type: NodePort 
  selector:
    app: javawebapp
  ports:
  - port: 80 #serviceport
    targetPort: 8080 #containerport
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: javawebapphpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: ReplicaSet
    name: javawebapprs
  minReplicas: 1
  maxReplicas: 2
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 50
